sonar.projectKey=qispring_url-link-extractor
sonar.organization=qispring
sonar.projectName=url-link-extractor
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=py
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
